on:
  issues:
    types:
      - opened
jobs:
  show-metadata:
    runs-on: ubuntu-latest
    steps:
    # Use environment variable to print the metadata (cf. https://github.com/actions/runner/issues/1656#issuecomment-1030077729).
    - name: Show metadata
      run: echo $JSON
      env:
        JSON: ${{ toJson(github.event) }}
  add-label:
    runs-on: ubuntu-latest
    steps:
    - name: Add label
      uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: '👀 requires attention'
