# Contrinuous Integration for the core package

name: testcontainers core
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        runtime:
#        - machine: ubuntu-latest
#          python-version: "3.7"
#        - machine: ubuntu-latest
#          python-version: "3.8"
          - machine: ubuntu-latest
            python-version: "3.9"
#        - machine: ubuntu-latest
#          python-version: "3.10"
#        - machine: ubuntu-latest
#          python-version: "3.11"
    runs-on: ${{ matrix.runtime.machine }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Poetry
        run: pipx install poetry
      - name: Setup python ${{ matrix.runtime.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.runtime.python-version }}
          cache: poetry
      - name: Install Python dependencies
        run: poetry install
      - name: Run tests
        run: make core/tests